
# Python的Sync与Async执行速度的快慢

## 前记
Python3 的版本中支持了 `async/await` 语法， 很多文章都在说这种语法的实现代码会变得很快， 但是这种快是有场景限制的。
这篇文章将尝试简单的解释为何`Async`的代码在某些场景比`Sync`的代码快。

## 4种函数类型
```python
# 1. 普通函数 FunctionType
def function():
    return 1

# 2. 生成器函数 GeneratorType
def generator():
    yield 2

# async修饰将普通函数和生成器函数包装成异步函数和异步生成器
# 3. 异步函数（协程） ：CoroutineType
async def async_function():
    return 3

# 4. 异步生成器 ： AsyncGeneratorType
async def async_generator():
    yield 4


# 通过类型判断可以验证函数的类型
import types
print(isinstance(function, types.FunctionType))  # True
print(isinstance(generator, types.FunctionType))  # True
print(isinstance(async_function, types.FunctionType))  # True
print(isinstance(async_generator, types.FunctionType))  # True

print(type(generator()), isinstance(generator(), types.GeneratorType))  # <class 'generator'> True
print(type(async_function()), isinstance(async_function(), types.CoroutineType))  # <class 'coroutine'> True
print(type(async_generator()), isinstance(async_generator(), types.AsyncGeneratorType))  # <class 'async_generator'> True
```

直接调用异步函数不会返回结果，而是返回一个coroutine对象：
`print(async_function())  # <coroutine object async_function at 0x102ff67d8>`

协程需要通过其他方式来驱动，因此可以使用这个协程对象的send方法给协程发送一个值：
`print(async_function().send(None))`

不幸的是，如果通过上面的调用会抛出一个异常：
`StopIteration: 3`

因为生成器/协程在正常返回退出时会抛出一个`StopIteration`异常，而原来的返回值会存放在`StopIteration`对象的value属性中  

通过新建一个run函数来驱动协程函数：
```python
def run(coroutine):
    try:
        result = coroutine.send(None)
        print('run:', result)
    except StopIteration as e:
        print('StopIteration:', e.value)

async def async_function():
    return 3

run(async_function())  # 打印: StopIteration: 3
```

# `await`语法
只能出现在通过`async`修饰的函数中，否则会报`SyntaxError`错误。

而且`await`后面的对象需要是一个`Awaitable`，或者实现了相关的协议。

查看`Awaitable`抽象类的代码，表明了只要一个类实现了`__await__`方法，那么通过它构造出来的实例就是一个`Awaitable`：
```python
import abc
class Awaitable(metaclass=abc.ABCMeta):
    __slots__ = ()

    @abc.abstractmethod
    def __await__(self):
        yield

    @classmethod
    def __subclasshook__(cls, C):
        if cls is Awaitable:
            return _check_methods(C, "__await__")
        return NotImplemented
```

`async`也可以应用到上下文管理器中，`__aenter__`和`__aexit__`需要返回一个`Awaitable`：
```python
import time
import asyncio

class GameContext:
    async def __aenter__(self):
        self._started = time.time()
        print('game loading...')
        await asyncio.sleep(1)
        self.data = 'game data'
        return self  # 这个返回值，会传给as后面的变量

    async def __aexit__(self, exc_type, exc, tb):
        print('game exit...')
        await asyncio.sleep(1)

    # async修饰符也能用在__call__方法上，表示这个方法是一个协程
    async def __call__(self, *args, **kws):
        if args[0] == 'time':
            return time.time() - self._started

async def game():
    async with GameContext() as ctx:
        print('game start...', ctx.data)
        await asyncio.sleep(2)
        print('game time: ', await ctx('time'))

asyncio.run(game())
'''打印：
game loading...
game start... game data
game time:  3.003209114074707
game exit...
'''
```

# `yield from`
Python3.3的`yield from`语法可以把生成器的操作委托给另一个生成器，生成器的调用方可以直接与子生成器进行通信
```python
def sub_gen():
    yield 1
    yield 2
    yield 3

def gen():
    return (yield from sub_gen())

def main():
    for val in gen():
        print(val)

main()  # 打印: 1 2 3
```

利用这一特性，使用`yield from`能够编写出类似协程效果的函数调用，在3.5之前，`asyncio`正是使用`@asyncio.coroutine`和`yield from`语法来创建协程

然而，用`yield from`容易在表示协程和生成器中混淆，没有良好的语义性，所以在Python 3.5推出了`async/await`表达式来作为协程的语法。

因此类似以下的调用是等价的：
```python
async with lock:
    ...

with (yield from lock):
    ...
######################
def main():
    return (yield from coro())

def main():
    return (await coro())
```

完成异步的代码不一定要用`async/await`，使用了`async/await`的代码也不一定能做到异步，  
`async/await`是协程的语法糖，使协程之间的调用变得更加清晰，  
使用`async`修饰的函数调用时会返回一个协程对象，`await`只能放在`async`修饰的函数里面使用，  
`await`后面必须要跟着一个协程对象或`Awaitable`，`await`的目的是等待协程控制流的返回，而实现暂停并挂起函数的操作是`yield`


